### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by lioramilbaum** [Code-Collaborate-Community/baboon#6]

**Comment by kittyweg** [comment]
I'm on it.

**Comment by lioramilbaum** [comment]
I don't see a PR is waiting for my review

**Comment by kittyweg** [comment]
![license](https://user-images.githubusercontent.com/48317904/71641471-2a5a2c00-2ca5-11ea-8ccf-454dbb959a32.png)

**Comment by kittyweg** [comment]
[kweg@kweg baboon]$ git pull
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From github.com:kittyweg/baboon
 * [new branch]      add-license-1 -> origin/add-license-1
 * [new branch]      patch-1       -> origin/patch-1
Already up to date.
[kweg@kweg baboon]$ git log
commit 02019b3d77ff1d9ed8f84d3eb0df7335704c55ab (HEAD -> master, origin/master, origin/HEAD)
Author: Kitty Weg <kweg@redhat.com>
Date:   Wed Jan 1 14:58:36 2020 +0200

    this is my first license github commit

commit 6a1686eb8b168f5206d212d4e15410e9d0d0ce34
Author: Kitty Weg <kweg@redhat.com>
Date:   Mon Dec 30 13:19:21 2019 +0200

    this is my first github commit

commit 6f46f65c8cea791f09d79650afc581dfdb19ae35
Author: Liora Milbaum <lmilbaum@redhat.com>
Date:   Mon Dec 30 12:37:39 2019 +0200

    first commit
[kweg@kweg baboon]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[kweg@kweg baboon]$

**Comment by kittyweg** [comment]
[kweg@kweg baboon]$ vi LICENSE.md
[kweg@kweg baboon]$ ll
total 40
-rw-rw-r--. 1 kweg kweg 35191 Jan  1 14:56 LICENSE.md
-rw-rw-r--. 1 kweg kweg    39 Dec 30 13:18 README.md
[kweg@kweg baboon]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	LICENSE.md

nothing added to commit but untracked files present (use "git add" to track)
[kweg@kweg baboon]$ git add LICENSE.md 
[kweg@kweg baboon]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   LICENSE.md

[kweg@kweg baboon]$ git commit -m "this is my first license github commit"
[master 02019b3] this is my first license github commit
 1 file changed, 679 insertions(+)
 create mode 100644 LICENSE.md
[kweg@kweg baboon]$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
[kweg@kweg baboon]$ git push origin master
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 12.14 KiB | 6.07 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To github.com:kittyweg/baboon.git
   6a1686e..02019b3  master -> master
[kweg@kweg baboon]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[kweg@kweg baboon]$ git pull
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From github.com:kittyweg/baboon
 * [new branch]      add-license-1 -> origin/add-license-1
 * [new branch]      patch-1       -> origin/patch-1
Already up to date.
[kweg@kweg baboon]$ git log
commit 02019b3d77ff1d9ed8f84d3eb0df7335704c55ab (HEAD -> master, origin/master, origin/HEAD)
Author: Kitty Weg <kweg@redhat.com>
Date:   Wed Jan 1 14:58:36 2020 +0200

    this is my first license github commit

commit 6a1686eb8b168f5206d212d4e15410e9d0d0ce34
Author: Kitty Weg <kweg@redhat.com>
Date:   Mon Dec 30 13:19:21 2019 +0200

    this is my first github commit

commit 6f46f65c8cea791f09d79650afc581dfdb19ae35
Author: Liora Milbaum <lmilbaum@redhat.com>
Date:   Mon Dec 30 12:37:39 2019 +0200

    first commit
[kweg@kweg baboon]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[kweg@kweg baboon]$

**Comment by lioramilbaum** [comment]
Go to GitHub web console and create a PR

**Comment by kittyweg** [comment]
I think it worked now.
